---
- name: Install ufw
  pacman:
    name: ufw
    state: present

- name: Deny all traffic
  ufw:
    default: deny

- name: Allow SSH
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Enable ufw
  ufw:
    state: enabled 
