---
- name: Create groups
  group:
    name: "{{ item }}"
    state: present
    system: no
  with_items: "{{ oyt_groups }}"

- name: Create users
  user:
    name: "{{ item.key }}"
    group: users
    groups: "{{ item.value.groups | join(',') }}"
    comment: "{{ item.value.name }}"
    shell: "{{ item.value.shell | default('/bin/bash') }}"
  with_dict: "{{ oyt_users }}"

- name: Create .ssh directories
  file:
    path: "/home/{{ item.key }}/.ssh"
    state: directory
    owner: "{{ item.key }}"
    group: users
    mode: "0700"
  with_dict: "{{ oyt_users }}"

- name: Configure ssh keys
  copy:
    src: "{{ inventory_dir }}/pubkeys/{{ item.value.ssh_key }}"
    dest: "/home/{{ item.key }}/.ssh/authorized_keys"
    owner: "{{ item.key }}"
    group: users
    mode: "0600"
  with_dict: "{{ oyt_users }}"
